### PR TITLE
Remove olds specs

### LINKED ISSUE #19: Remove failing specs after User model deletion

### PR DESCRIPTION
**Pull request by juanmferreira93**
Resolve #19 

I remove specs that are failing cause we delete User model and related stuffs.

Please take a carefully look at this.

### CODE REVIEW

File: spec/policies/admin/application_policy_spec.rb [hunk 1]
```diff
@@ -9,20 +9,12 @@
...
-        expect(subject).not_to permit(user, user)
-      end
-    end
   end
 
   describe 'scope' do
     let(:admin) { create(:admin_user) }
     let(:mock_model) { double('MockModel', all: true) }
-    subject { ApplicationPolicy::Scope.new(admin, mock_model).resolve }
+    subject { Admin::ApplicationPolicy::Scope.new(admin, mock_model).resolve }
```
Comment (juanmferreira93) [inline spec/policies/admin/application_policy_spec.rb:17]: Im not sure about this

**Review by GuilleLeopold — APPROVED** [review]

**Review by jpascual1994 — APPROVED** [review]
